name: Run Job Notifications Script

on:
  push:
    branches:
      - master
  workflow_dispatch: # To allow manual triggers
  schedule:
    - cron: "0 * * * *" # Runs every hour

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Debug and Print Environment Variables
        run: |
          echo "SMTP_PORT: $SMTP_PORT"
          echo "SMTP_SERVER: $SMTP_SERVER"
          echo "SENDER_EMAIL: $SENDER_EMAIL"
          echo "RECEIVER_EMAILS: $RECEIVER_EMAILS"
          echo "EMAIL_PASSWORD: [REDACTED]"
        env:
          SMTP_PORT: "587"
          SMTP_SERVER: "smtp.gmail.com"
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          RECEIVER_EMAILS: ${{ secrets.RECEIVER_EMAILS }}

      - name: Run job alert script
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          RECEIVER_EMAILS: ${{ secrets.RECEIVER_EMAILS }}
        run: python jobalert.py
