name: Run Job Notifications Script

on:
  workflow_dispatch:  # Allows manual trigger
  schedule:
    - cron: "0 */2 * * *"  # Runs every 2 hours

jobs:
  run-script:
    runs-on: ubuntu-22.04 

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
  
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
  
      - name: Install dependencies
        run: pip install -r requirements.txt
  
      - name: Load .env file and run script
        run: |
          export $(cat .env | xargs)  # Load .env variables into the environment
          python jobalert.py